### ISSUE TITLE
Comment Mailing

### ISSUE THREAD

**Issue by jsobers1331** [yii2mod/yii2-comments#18]
Hi ,

Just wondering if you can add the ability to send emails on comment addition or replies to any parent comment within your module.

Sounds like a useful enhancement.

Giving configuration option to disable to enable email to parent comment for replies or comments in general.

what do you think?

**Comment by ihorchepurnyi** [comment]
Hi, it's interesting. How it will look on the frontend and do we need to change the Commnet table structure? Maybe we can add this enhancement to the admin panel on the edit single comment page.

**Comment by ihorchepurnyi** [comment]
I'm not sure that this functionality is needed for the basic comments widget. Can you provide some links to the projects with the ability to send the emails via commets?

**Comment by jsobers1331** [comment]
I haven't implemented it yet. I'm currently looking into ways on how to do it with your current module structure.

**Comment by ihorchepurnyi** [comment]
@disem what do you think about it?

**Comment by disem** [comment]
This is not the feature that should be included in the simple comments widget. There are several problems that will be caused by this feature
- Should we send an email within request or process it by worker?
- What should we do if there are a lot of responses to the single comment?
- Should we provide an option to disable email notifications per each user?
- Etc

Each project will probably have their own requirements to the notifications, we can't cover all of them.
If we'll do this, it should be a separate extension to allow usage of current comments module as is.

**Comment by ihorchepurnyi** [comment]
@disem thanks, i agree with you
